types <- c(
  "run: int64",
  "time: int64",
  "id_Person: int64",
  "L1_potentialHourlyEarnings: double",
  "adultchildflag: bool",
  "countFemale: int64",
  "countMale: int64",
  "countNaN: int64",
  "countOK: int64",
  "countOKover32: int64",
  "covidModuleGrossLabourIncomeBaseline_Xt5: string",
  "dag: int64",
  "dcpagdf: double",
  "dcpen: bool",
  "dcpex: bool",
  "dcpst: string",
  "dcpyy: double",
  "ded: bool",
  "deh_c3: string",
  "dehf_c3: string",
  "dehm_c3: string",
  "dehsp_c3: string",
  "der: bool",
  "dgn: string",
  "dhe: double",
  "dhesp: double",
  "dhh_owned: bool",
  "dhm: double",
  "dhm_ghq: bool",
  "dlltsd: bool",
  "education_inrange: bool",
  "flagAlignEntry: double",
  "flagAlignExit: double",
  "flagDies: double",
  "flagEmigrate: double",
  "flagImmigrate: double",
  "hoursWorkedWeekly: double",
  "household_status: string",
  "idBenefitUnit: int64",
  "idFather: double",
  "idMother: double",
  "idPartner: double",
  "id_original: double",
  "inverseMillsRatioMaxFemale: double",
  "inverseMillsRatioMaxMale: double",
  "inverseMillsRatioMinFemale: double",
  "inverseMillsRatioMinMale: double",
  "labourSupplyWeekly: string",
  "les_c4: string",
  "les_c7_covid: double",
  "lesdf_c4: string",
  "lessp_c4: string",
  "partnership_samesex: bool",
  "potentialHourlyEarnings: double",
  "sIndex: double",
  "sIndexNormalised: double",
  "scoreFemale: int64",
  "scoreMale: int64",
  "sedex: bool",
  "weight: int64",
  "women_fertility: bool",
  "yearlyEquivalisedConsumption: double",
  "ynbcpdf_dv: double",
  "yplgrs_dv: double",
  "ypnbihs_dv: double",
  "ypncp: double",
  "ypnoab: double",
  "yptciihs_dv: double"
)

types |> 
  str_replace_all("^", "(\"") |> 
  str_replace_all(":", "\",") |> 
  str_replace_all("double", "pa.float64()),") |> 
  str_replace_all("int64", "pa.int64()),") |> 
  str_replace_all("bool", "pa.bool_()),") |> 
  str_replace_all("string", "pa.string()),") |> 
  cat(sep = "\n")
